name: Build Vercel

on:
  push:
    branches-ignore:
      - vercel
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - '.docker/**'
      - '.devcontainer/**'
      - '.github/**'

env:
  NODE_VERSION: "22.14.0"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install npm dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ITEM
          path: |
            ./theme/*

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: vercel

      - name: Clean up
        run: |
          rm -rf usr/themes/ITEM

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ITEM
          path: usr/themes/ITEM

      - name: Commit Snapshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: build with ${{ github.sha }}
          branch: vercel
          skip_dirty_check: true
          push_options: '--force'
          create_branch: true
          skip_fetch: true
          skip_checkout: true
          commit_options: '--allow-empty'
